// src/pages/game/timeQuestions.js
export const timePool = [
  { id: "t-1", q: "อินทิกรัลของ 2x dx คืออะไร", choices: ["x² + C", "2x² + C", "x³ + C", "ln(x) + C"], answer: 0 },
  { id: "t-2", q: "แรงไฟฟ้าวัดเป็นหน่วยใด", choices: ["Watt", "Ampere", "Volt", "Ohm"], answer: 2 },
  { id: "t-3", q: "ค่าคงที่ของแรงโน้มถ่วงสัญลักษณ์ใด", choices: ["G", "g", "F", "M"], answer: 1 },
  { id: "t-4", q: "ในวงจรไฟฟ้า R=V/I หมายถึงกฎของใคร", choices: ["Faraday", "Ohm", "Newton", "Ampere"], answer: 1 },
  { id: "t-5", q: "ภาษา Python ใช้สัญลักษณ์ใดในการคอมเมนต์", choices: ["//", "/* */", "#", "--"], answer: 2 },
  { id: "t-6", q: "ลูปที่ทำซ้ำจนกว่าจะเป็นเท็จคือ", choices: ["if", "for", "while", "switch"], answer: 2 },
  { id: "t-7", q: "ชนิดข้อมูลที่เก็บข้อความใน C คือ", choices: ["int", "char", "float", "string"], answer: 1 },
  { id: "t-8", q: "คิว (Queue) ใช้หลักการใด", choices: ["LIFO", "FIFO", "FILO", "Random"], answer: 1 },
  { id: "t-9", q: "อัลกอริทึมใดที่ใช้แนวคิดแบ่งครึ่งข้อมูล", choices: ["Linear Search", "Binary Search", "Bubble Sort", "Insertion Sort"], answer: 1 },
  { id: "t-10", q: "ฟังก์ชันใดใช้สำหรับหาความยาวของสตริงใน C", choices: ["strlen()", "sizeof()", "len()", "count()"], answer: 0 },
  { id: "t-11", q: "ระบบดิจิทัลใช้ข้อมูลพื้นฐานแบบใด", choices: ["ฐานสิบ", "ฐานแปด", "ฐานสอง", "ฐานสิบหก"], answer: 2 },
  { id: "t-12", q: "ส่วนประกอบใดทำหน้าที่เก็บคำสั่งและข้อมูลในคอมพิวเตอร์", choices: ["CPU", "Memory", "GPU", "Cache"], answer: 1 },
  { id: "t-13", q: "หน่วยใดเล็กที่สุดในหน่วยความจำ", choices: ["Bit", "Byte", "KB", "MB"], answer: 0 },
  { id: "t-14", q: "CPU ย่อมาจากอะไร", choices: ["Central Processing Unit", "Control Processing Unit", "Central Program Unit", "Compute Process Unit"], answer: 0 },
  { id: "t-15", q: "ระบบปฏิบัติการทำหน้าที่หลักคือ", choices: ["แสดงผลกราฟิก", "จัดการทรัพยากร", "เขียนโปรแกรม", "ออกแบบวงจร"], answer: 1 },
  { id: "t-16", q: "หน่วยความจำที่เก็บข้อมูลชั่วคราวคือ", choices: ["ROM", "RAM", "SSD", "Cache"], answer: 1 },
  { id: "t-17", q: "ระบบฐานข้อมูลมีองค์ประกอบหลักกี่ส่วน", choices: ["2", "3", "4", "5"], answer: 2 },
  { id: "t-18", q: "SQL ย่อมาจากอะไร", choices: ["Structured Query Language", "System Query Logic", "Simple Quick Language", "Standard Query List"], answer: 0 },
  { id: "t-19", q: "คำสั่ง SQL ที่ใช้ลบข้อมูลคือ", choices: ["DELETE", "REMOVE", "DROP", "CLEAR"], answer: 0 },
  { id: "t-20", q: "รูปแบบเครือข่ายใดเชื่อมต่อศูนย์กลางกลาง", choices: ["Star", "Bus", "Ring", "Mesh"], answer: 0 },
  { id: "t-21", q: "IPv6 มีขนาดกี่บิต", choices: ["32", "64", "128", "256"], answer: 2 },
  { id: "t-22", q: "โปรโตคอลใดใช้สำหรับรับส่งอีเมล", choices: ["HTTP", "FTP", "SMTP", "SNMP"], answer: 2 },
  { id: "t-23", q: "ฟังก์ชัน Probability มีค่าระหว่างใด", choices: ["0 ถึง 1", "1 ถึง 10", "-1 ถึง 1", "ไม่มีขอบเขต"], answer: 0 },
  { id: "t-24", q: "ค่าเฉลี่ยเลขคณิตคือ", choices: ["ผลรวม/จำนวนข้อมูล", "ค่ามากสุด", "ค่าน้อยสุด", "ผลต่าง"], answer: 0 },
  { id: "t-25", q: "ในการวัดค่ากระแสไฟฟ้าใช้เครื่องมือใด", choices: ["Voltmeter", "Ohmmeter", "Ammeter", "Thermometer"], answer: 2 },
  { id: "t-26", q: "สมการ y = mx + c เป็นสมการของอะไร", choices: ["เส้นตรง", "พาราโบลา", "วงกลม", "วงรี"], answer: 0 },
  { id: "t-27", q: "ในวงจร Logic ‘AND’ จะให้ค่า True เมื่อใด", choices: ["อย่างน้อย 1 True", "ทั้งหมด True", "ทั้งหมด False", "True และ False"], answer: 1 },
  { id: "t-28", q: "ไมโครคอนโทรลเลอร์แตกต่างจากไมโครโปรเซสเซอร์เพราะ", choices: ["ไม่มีหน่วยความจำ", "รวมหน่วยความจำไว้ภายใน", "ใช้ได้เฉพาะคอมพิวเตอร์", "ไม่สามารถโปรแกรมได้"], answer: 1 },
  { id: "t-29", q: "ตัวต้านทานมีหน้าที่อะไร", choices: ["เก็บประจุ", "ต้านกระแส", "ขยายสัญญาณ", "เปลี่ยนพลังงาน"], answer: 1 },
  { id: "t-30", q: "หน่วย SI ของความต่างศักย์คือ", choices: ["W", "V", "A", "Ω"], answer: 1 },
  { id: "t-31", q: "สูตรพลังงานศักย์โน้มถ่วงคือ", choices: ["mgh", "1/2mv²", "qV", "F=ma"], answer: 0 },
  { id: "t-32", q: "แผงวงจรในระบบดิจิทัลเรียกว่า", choices: ["PCB", "IC", "RAM", "ROM"], answer: 0 },
  { id: "t-33", q: "โปรแกรมควบคุมหุ่นยนต์เรียกว่า", choices: ["Robot OS", "Controller Program", "Automation System", "Embedded Code"], answer: 3 },
  { id: "t-34", q: "ระบบฝังตัว (Embedded System) คืออะไร", choices: ["ระบบที่มี OS เต็มรูปแบบ", "ระบบเฉพาะงาน", "ระบบเครือข่าย", "ระบบฐานข้อมูล"], answer: 1 },
  { id: "t-35", q: "การโจมตีแบบ Phishing คือ", choices: ["ขโมยรหัสผ่านด้วยอีเมลปลอม", "โจมตีเครือข่ายโดยตรง", "เข้ารหัสข้อมูลเรียกค่าไถ่", "แทรกโค้ดในระบบ"], answer: 0 },
  { id: "t-36", q: "Firewall ทำหน้าที่อะไร", choices: ["ป้องกันไวรัส", "กรองการเชื่อมต่อ", "ลบไฟล์", "บันทึกข้อมูล"], answer: 1 },
  { id: "t-37", q: "ซอฟต์แวร์ประเภทใดใช้พัฒนาโปรแกรม", choices: ["Application", "Compiler", "Utility", "Driver"], answer: 1 },
  { id: "t-38", q: "OOP ย่อมาจากอะไร", choices: ["Object Oriented Programming", "Open Object Process", "Object Operation Program", "Output Oriented Programming"], answer: 0 },
  { id: "t-39", q: "ฟังก์ชันหลักของ OS คือข้อใด", choices: ["Scheduling", "Debugging", "Encrypting", "Designing"], answer: 0 },
  { id: "t-40", q: "โปรแกรมจำลองเครื่องเสมือนเรียกว่า", choices: ["Compiler", "Virtual Machine", "Interpreter", "Debugger"], answer: 1 },
  { id: "t-41", q: "คำว่า 'Algorithm' หมายถึงอะไร", choices: ["ภาษาคอมพิวเตอร์", "ลำดับขั้นตอนแก้ปัญหา", "หน่วยความจำ", "เครื่องคำนวณ"], answer: 1 },
  { id: "t-42", q: "หน่วยใดใน CPU ทำหน้าที่คำนวณ", choices: ["CU", "ALU", "MU", "BU"], answer: 1 },
  { id: "t-43", q: "โปรแกรมที่แปลภาษาระดับสูงเป็นระดับต่ำคือ", choices: ["Interpreter", "Compiler", "Assembler", "Linker"], answer: 1 },
  { id: "t-44", q: "RAM แบบไม่ลบข้อมูลเมื่อปิดเครื่องคือ", choices: ["SRAM", "DRAM", "EEPROM", "Flash"], answer: 3 },
  { id: "t-45", q: "เซนเซอร์คืออะไร", choices: ["อุปกรณ์ควบคุมมอเตอร์", "อุปกรณ์ตรวจจับข้อมูล", "หน่วยความจำ", "วงจรขยายสัญญาณ"], answer: 1 },
  { id: "t-46", q: "PLC ใช้ในงานใด", choices: ["งานคำนวณ", "งานควบคุมอัตโนมัติ", "งานออกแบบกราฟิก", "งานจัดเก็บข้อมูล"], answer: 1 },
  { id: "t-47", q: "Robot Arm ใช้หลักการทำงานของมอเตอร์ใด", choices: ["DC", "AC", "Stepper", "Servo"], answer: 3 },
  { id: "t-48", q: "Cybersecurity มีหน้าที่หลักคือ", choices: ["สร้างเว็บไซต์", "ป้องกันภัยในระบบคอมพิวเตอร์", "ออกแบบซอฟต์แวร์", "จัดการฐานข้อมูล"], answer: 1 },
  { id: "t-49", q: "การเข้ารหัสข้อมูลคืออะไร", choices: ["การแปลงข้อมูลให้อ่านได้", "การแปลงข้อมูลให้อ่านไม่ได้", "การลบข้อมูล", "การคัดลอกข้อมูล"], answer: 1 },
  { id: "t-50", q: "โปรโตคอลใดใช้เข้ารหัสการสื่อสารบนเว็บ", choices: ["HTTP", "HTTPS", "FTP", "SMTP"], answer: 1 },
  { id: "t-51", q: "การคูณเมทริกซ์ต้องมีเงื่อนไขใดถูกต้อง", choices: ["จำนวนแถวเท่ากัน", "จำนวนคอลัมน์ของ A เท่ากับแถวของ B", "ขนาดเท่ากัน", "ไม่มีเงื่อนไข"], answer: 1 },
  { id: "t-52", q: "RAM และ ROM ต่างกันที่อะไร", choices: ["RAM เก็บข้อมูลถาวร", "ROM เขียนซ้ำได้", "RAM เก็บข้อมูลชั่วคราว", "ROM เป็นแบบไร้สาย"], answer: 2 },
  { id: "t-53", q: "ฟังก์ชัน hash ใช้ในงานใด", choices: ["แปลงข้อมูลเป็นค่าเฉพาะ", "คำนวณสถิติ", "สร้างรหัสผ่าน", "แปลภาษา"], answer: 0 },
  { id: "t-54", q: "คำสั่ง SQL ที่ใช้สร้างตารางคือ", choices: ["CREATE TABLE", "MAKE TABLE", "NEW TABLE", "INIT TABLE"], answer: 0 },
  { id: "t-55", q: "โครงสร้างข้อมูลใดเหมาะกับการเรียงข้อมูลแบบเรียงลำดับ", choices: ["Array", "Stack", "Tree", "Graph"], answer: 2 },
  { id: "t-56", q: "คำว่า Firmware หมายถึงอะไร", choices: ["โปรแกรมพื้นฐานในฮาร์ดแวร์", "โปรแกรมในระบบปฏิบัติการ", "ไฟล์ซอฟต์แวร์ทั่วไป", "โปรแกรมจำลอง"], answer: 0 },
  { id: "t-57", q: "ระบบไฟฟ้า DC หมายถึง", choices: ["ไฟฟ้าสลับ", "ไฟฟ้าตรง", "ไฟฟ้าแรงสูง", "ไฟฟ้าควบคุม"], answer: 1 },
  { id: "t-58", q: "ฟังก์ชัน Random ใช้สำหรับอะไร", choices: ["คำนวณค่าเฉลี่ย", "สุ่มตัวเลข", "หาค่าสูงสุด", "จัดเรียงข้อมูล"], answer: 1 },
  { id: "t-59", q: "คำว่า Boolean หมายถึงข้อมูลชนิดใด", choices: ["ตัวเลข", "ข้อความ", "จริงหรือเท็จ", "จำนวนทศนิยม"], answer: 2 },
  { id: "t-60", q: "โปรแกรมใดใช้สำหรับพัฒนาเว็บ", choices: ["Photoshop", "VS Code", "MS Word", "PowerPoint"], answer: 1 },
  { id: "t-61", q: "ความถี่ไฟฟ้ากระแสสลับในประเทศไทยคือ", choices: ["50 Hz", "60 Hz", "45 Hz", "100 Hz"], answer: 0 },
  { id: "t-62", q: "สัญลักษณ์ Σ ใช้ในคณิตศาสตร์เพื่อหมายถึงอะไร", choices: ["ค่าเฉลี่ย", "ผลรวม", "ผลต่าง", "ค่าเฉลี่ยเลขคณิต"], answer: 1 },
  { id: "t-63", q: "ตัวเก็บประจุทำหน้าที่อะไร", choices: ["ต้านกระแส", "เก็บพลังงานชั่วคราว", "ขยายสัญญาณ", "กรองสัญญาณ"], answer: 1 },
  { id: "t-64", q: "หน่วยของความต้านทานคือ", choices: ["V", "W", "A", "Ω"], answer: 3 },
  { id: "t-65", q: "AI ที่ใช้ในการควบคุมหุ่นยนต์เรียกว่าอะไร", choices: ["Robotic AI", "Control AI", "Embedded AI", "Mechanical AI"], answer: 0 },
  { id: "t-66", q: "Which law relates voltage, current, and resistance?", choices: ["Ohm's Law", "Faraday's Law", "Kirchhoff's Law", "Ampere's Law"], answer: 0 },
  { id: "t-67", q: "What is the derivative of sin(x)?", choices: ["cos(x)", "-cos(x)", "-sin(x)", "tan(x)"], answer: 0 },
  { id: "t-68", q: "Which data structure uses LIFO principle?", choices: ["Queue", "Stack", "Array", "Graph"], answer: 1 },
  { id: "t-69", q: "Which layer of OSI handles routing?", choices: ["Application", "Network", "Transport", "Session"], answer: 1 },
  { id: "t-70", q: "Which sorting algorithm is fastest on average?", choices: ["Bubble Sort", "Selection Sort", "Quick Sort", "Insertion Sort"], answer: 2 },
  { id: "t-71", q: "What is the unit of electric current?", choices: ["Volt", "Ampere", "Ohm", "Watt"], answer: 1 },
  { id: "t-72", q: "Which SQL command is used to retrieve data?", choices: ["SELECT", "INSERT", "UPDATE", "DELETE"], answer: 0 },
  { id: "t-73", q: "In programming, what does IDE stand for?", choices: ["Integrated Development Environment", "Interactive Data Engine", "Input Device Emulator", "Intelligent Design Editor"], answer: 0 },
  { id: "t-74", q: "What is the main function of the OS?", choices: ["Managing resources", "Running programs", "Designing circuits", "Compiling code"], answer: 0 },
  { id: "t-75", q: "Which protocol is used for secure web communication?", choices: ["HTTP", "HTTPS", "FTP", "DNS"], answer: 1 },
  { id: "t-76", q: "Which device converts AC to DC?", choices: ["Transformer", "Rectifier", "Inductor", "Capacitor"], answer: 1 },
  { id: "t-77", q: "What does CPU stand for?", choices: ["Central Processing Unit", "Core Program Unit", "Computer Power Unit", "Central Power Unit"], answer: 0 },
  { id: "t-78", q: "Which of the following is NOT a programming language?", choices: ["Python", "C++", "HTML", "Java"], answer: 2 },
  { id: "t-79", q: "Which part of the CPU performs arithmetic operations?", choices: ["CU", "ALU", "MU", "Cache"], answer: 1 },
  { id: "t-80", q: "Which is an example of an operating system?", choices: ["Windows", "Oracle", "Python", "Visual Studio"], answer: 0 },
  { id: "t-81", q: "Which symbol is used for comments in Python?", choices: ["//", "#", "--", "/* */"], answer: 1 },
  { id: "t-82", q: "What does SQL stand for?", choices: ["Structured Query Language", "Simple Query Logic", "System Query Level", "Standard Quick Language"], answer: 0 },
  { id: "t-83", q: "Which memory is volatile?", choices: ["ROM", "RAM", "Flash", "Hard Disk"], answer: 1 },
  { id: "t-84", q: "Which gate gives output 1 only if all inputs are 1?", choices: ["AND", "OR", "XOR", "NAND"], answer: 0 },
  { id: "t-85", q: "What is the hexadecimal of binary 1111?", choices: ["E", "F", "A", "B"], answer: 1 },
  { id: "t-86", q: "Which algorithm is used for shortest path?", choices: ["Kruskal", "Dijkstra", "Prim", "Bellman-Ford"], answer: 1 },
  { id: "t-87", q: "Which device is used to store permanent data?", choices: ["RAM", "ROM", "Cache", "Register"], answer: 1 },
  { id: "t-88", q: "Which component controls the flow of current?", choices: ["Resistor", "Capacitor", "Diode", "Transistor"], answer: 0 },
  { id: "t-89", q: "Which is NOT a cyber attack?", choices: ["Phishing", "Brute Force", "Encryption", "DDoS"], answer: 2 },
  { id: "t-90", q: "Which mathematical concept is used in probability?", choices: ["Integration", "Permutation", "Differentiation", "Equation"], answer: 1 },
  { id: "t-91", q: "Which microcontroller is commonly used in robotics?", choices: ["Arduino", "Router", "Modem", "GPU"], answer: 0 },
  { id: "t-92", q: "What is the main purpose of Cybersecurity?", choices: ["Data Protection", "Data Storage", "Data Sharing", "Data Compression"], answer: 0 },
  { id: "t-93", q: "Which number system is used in computers?", choices: ["Decimal", "Binary", "Octal", "Hexadecimal"], answer: 1 },
  { id: "t-94", q: "Which OS scheduling algorithm gives equal priority?", choices: ["FCFS", "Round Robin", "Priority", "SJF"], answer: 1 },
  { id: "t-95", q: "Which software development model uses iterations?", choices: ["Waterfall", "Agile", "V-Model", "Spiral"], answer: 1 },
  { id: "t-96", q: "Which logic gate represents addition in binary?", choices: ["AND", "OR", "XOR", "NOT"], answer: 2 },
  { id: "t-97", q: "Which is a non-relational database?", choices: ["MySQL", "MongoDB", "PostgreSQL", "SQLite"], answer: 1 },
  { id: "t-98", q: "Which component is used to amplify signals?", choices: ["Resistor", "Capacitor", "Transistor", "Inductor"], answer: 2 },
  { id: "t-99", q: "Which programming paradigm uses classes and objects?", choices: ["Functional", "OOP", "Procedural", "Declarative"], answer: 1 },
  { id: "t-100", q: "Which device provides power to a circuit?", choices: ["Battery", "Resistor", "Diode", "Transistor"], answer: 0 },
];


